--
-- FS25 CustomContracts
--
-- @Author: Racc00n
--

CreateInvoiceEvent = {}
local CreateInvoiceEvent_mt = Class(CreateInvoiceEvent, Event)

InitEventClass(CreateInvoiceEvent, "CreateInvoiceEvent")

function CreateInvoiceEvent.emptyNew()
  return Event.new(CreateInvoiceEvent_mt)
end

function CreateInvoiceEvent.new(payload, farmId)
  local self = CreateInvoiceEvent.emptyNew()
  self.payload = payload
  self.farmId = farmId
  return self
end

function CreateInvoiceEvent:writeStream(streamId, connection)
  streamWriteInt32(streamId, self.farmId)
  streamWriteInt32(streamId, self.payload.receiverFarmId or -1)
  streamWriteString(streamId, self.payload.title or "")
  streamWriteString(streamId, self.payload.description or "")
  streamWriteInt32(streamId, self.payload.total or 0)
  streamWriteInt32(streamId, self.payload.dueAt or 0)
  streamWriteInt32(streamId, self.payload.relatedContractId or -1)
  streamWriteBool(streamId, self.payload.autoGenerated == true)
end

function CreateInvoiceEvent:readStream(streamId, connection)
  self.farmId = streamReadInt32(streamId)

  self.payload = {
    receiverFarmId    = streamReadInt32(streamId),
    title             = streamReadString(streamId),
    description       = streamReadString(streamId),
    total             = streamReadInt32(streamId),
    dueAt             = streamReadInt32(streamId),
    relatedContractId = streamReadInt32(streamId),
    autoGenerated     = streamReadBool(streamId)
  }

  self:run(connection)
end

function CreateInvoiceEvent:run(connection)
  if not connection:getIsServer() then
    g_server:broadcastEvent(CreateInvoiceEvent.new(self.payload, self.farmId))
  end

  local farmId = self.farmId
  if farmId == nil or farmId == FarmManager.SPECTATOR_FARM_ID then
    return
  end

  local invoiceManager = g_currentMission.CustomContracts.InvoiceManager
  invoiceManager:handleCreateRequest(farmId, self.payload)
end
