--
-- FS25 Contract and Invoices
--
-- @Author: Racc00n
-- @Version: 1.0.0.0
--

EditInvoiceEvent = {}
local EditInvoiceEvent_mt = Class(EditInvoiceEvent, Event)

InitEventClass(EditInvoiceEvent, "EditInvoiceEvent")

function EditInvoiceEvent.emptyNew()
  local self = Event.new(EditInvoiceEvent_mt)
  self.lines = {}
  return self
end

function EditInvoiceEvent.new(invoiceId, invoiceData)
  local self             = EditInvoiceEvent.emptyNew()

  self.invoiceId         = invoiceId

  self.receiverFarmId    = invoiceData.receiverFarmId or -1
  self.title             = invoiceData.title or ""
  self.description       = invoiceData.description or ""
  self.total             = invoiceData.total or 0
  self.relatedContractId = invoiceData.relatedContractId or -1
  self.autoGenerated     = invoiceData.autoGenerated == true
  self.status            = invoiceData.status or Invoice.STATUS.DRAFT

  -- copy lines (avoid sharing references)
  self.lines             = {}
  local lines            = invoiceData.lines or {}
  for i = 1, #lines do
    local l = lines[i]
    self.lines[i] = {
      title  = l.title or "",
      amount = tonumber(l.amount) or 0
    }
  end

  return self
end

function EditInvoiceEvent:writeStream(streamId, connection)
  streamWriteInt32(streamId, self.invoiceId or -1)

  streamWriteInt32(streamId, self.receiverFarmId or -1)
  streamWriteString(streamId, self.title or "")
  streamWriteString(streamId, self.description or "")

  local lines = self.lines or {}
  streamWriteInt32(streamId, #lines)
  for i = 1, #lines do
    local l = lines[i]
    streamWriteString(streamId, l.title or "")
    streamWriteFloat32(streamId, tonumber(l.amount) or 0)
  end

  streamWriteInt32(streamId, self.total or 0)
  streamWriteInt32(streamId, self.relatedContractId or -1)
  streamWriteBool(streamId, self.autoGenerated == true)
  streamWriteString(streamId, self.status or Invoice.STATUS.DRAFT)
end

function EditInvoiceEvent:readStream(streamId, connection)
  self.invoiceId      = streamReadInt32(streamId)

  self.receiverFarmId = streamReadInt32(streamId)
  self.title          = streamReadString(streamId)
  self.description    = streamReadString(streamId)

  local lineCount     = streamReadInt32(streamId)
  self.lines          = {}
  for i = 1, lineCount do
    local t = streamReadString(streamId)
    local a = streamReadFloat32(streamId)
    self.lines[i] = { title = t, amount = a }
  end

  self.total             = streamReadInt32(streamId)
  self.relatedContractId = streamReadInt32(streamId)
  self.autoGenerated     = streamReadBool(streamId)
  self.status            = streamReadString(streamId)

  self:run(connection)
end

function EditInvoiceEvent:run(connection)
  if not connection:getIsServer() then
    g_server:broadcastEvent(EditInvoiceEvent.new(self.invoiceId, {
      receiverFarmId    = self.receiverFarmId,
      title             = self.title,
      description       = self.description,
      lines             = self.lines,
      total             = self.total,
      relatedContractId = self.relatedContractId,
      autoGenerated     = self.autoGenerated,
      status            = self.status
    }), nil, connection)
  end

  local invoiceManager = g_currentMission.CustomContracts.InvoiceManager
  invoiceManager:handleEditRequest(self.invoiceId, {
    receiverFarmId    = self.receiverFarmId,
    title             = self.title,
    description       = self.description,
    lines             = self.lines,
    total             = self.total,
    relatedContractId = self.relatedContractId,
    autoGenerated     = self.autoGenerated,
    status            = self.status
  })
end
