SyncInvoicesEvent = {}
local SyncInvoicesEvent_mt = Class(SyncInvoicesEvent, Event)

InitEventClass(SyncInvoicesEvent, "SyncInvoicesEvent")

function SyncInvoicesEvent.emptyNew()
  local self = Event.new(SyncInvoicesEvent_mt)
  return self
end

function SyncInvoicesEvent.new(invoices, nextId)
  local self = SyncInvoicesEvent.emptyNew()
  self.invoices = invoices
  self.nextId = nextId

  return self
end

function SyncInvoicesEvent:writeStream(streamId, connection)
  -- nextInvoiceId
  streamWriteInt32(streamId, self.nextId or 1)

  -- invoice count
  local count = table.size(self.invoices)
  streamWriteInt32(streamId, count)

  for _, invoice in pairs(self.invoices) do
    streamWriteInt32(streamId, invoice.id)
    streamWriteString(streamId, invoice.number or "")
    streamWriteInt32(streamId, invoice.creatorFarmId or -1)
    streamWriteInt32(streamId, invoice.receiverFarmId or -1)
    streamWriteString(streamId, invoice.status or Invoice.STATUS.DRAFT)
    streamWriteString(streamId, invoice.currency or "EUR")
    streamWriteInt32(streamId, invoice.createdAt or 0)
    streamWriteInt32(streamId, invoice.sentAt or 0)
    streamWriteInt32(streamId, invoice.dueAt or 0)
    streamWriteInt32(streamId, invoice.paidAt or 0)
    streamWriteString(streamId, invoice.title or "")
    streamWriteString(streamId, invoice.description or "")
    streamWriteInt32(streamId, invoice.total or 0)
    streamWriteInt32(streamId, invoice.paid or 0)
    streamWriteInt32(streamId, invoice.remaining or 0)
    streamWriteInt32(streamId, invoice.relatedContractId or -1)
    streamWriteBool(streamId, invoice.autoGenerated == true)
    streamWriteString(streamId, invoice.meta or "")
  end
end

function SyncInvoicesEvent:readStream(streamId, connection)
  self.nextId = streamReadInt32(streamId)
  local count = streamReadInt32(streamId)

  self.invoices = {}

  for i = 1, count do
    local id                = streamReadInt32(streamId)
    local number            = streamReadString(streamId)
    local creatorFarmId     = streamReadInt32(streamId)
    local receiverFarmId    = streamReadInt32(streamId)
    local status            = streamReadString(streamId)
    local currency          = streamReadString(streamId)
    local createdAt         = streamReadInt32(streamId)
    local sentAt            = streamReadInt32(streamId)
    local dueAt             = streamReadInt32(streamId)
    local paidAt            = streamReadInt32(streamId)
    local title             = streamReadString(streamId)
    local description       = streamReadString(streamId)
    local total             = streamReadInt32(streamId)
    local paid              = streamReadInt32(streamId)
    local remaining         = streamReadInt32(streamId)
    local relatedContractId = streamReadInt32(streamId)
    local autoGenerated     = streamReadBool(streamId)
    local meta              = streamReadString(streamId)

    local invoice           = Invoice.new(
      id,
      creatorFarmId,
      receiverFarmId,
      createdAt,
      sentAt,
      dueAt,
      paidAt,
      title,
      description,
      total,
      paid,
      relatedContractId ~= -1 and relatedContractId or nil,
      autoGenerated
    )

    invoice.number          = number
    invoice.status          = status
    invoice.currency        = currency or "EUR"
    invoice.remaining       = remaining or 0
    invoice.meta            = meta ~= "" and meta or nil

    self.invoices[id]       = invoice
  end

  self:run(connection)
end

function SyncInvoicesEvent:run(connection)
  local invoiceManager = g_currentMission.CustomContracts.InvoiceManager
  if invoiceManager == nil then
    return
  end

  invoiceManager.invoices = self.invoices
  invoiceManager.nextId = self.nextId

  g_messageCenter.publish(MessageType.INVOICES_UPDATED)
end
