--
-- FS25 CustomContracts
--
-- @Author: Racc00n
-- @Version: 0.0.1.1
--

CreateInvoiceDialog = {}
local CreateInvoiceDialog_mt = Class(CreateInvoiceDialog, MessageDialog)


function CreateInvoiceDialog.new(target, custom_mt)
  local self = MessageDialog.new(target, custom_mt or CreateInvoiceDialog_mt)

  self.invoiceDraft = {
    lines = {}
  }

  return self
end

function CreateInvoiceDialog:onCreate()
  CreateInvoiceDialog:superClass().onCreate(self)
  self.linesRenderer = InvoiceLinesRenderer.new()
end

function CreateInvoiceDialog:onGuiSetupFinished()
  CreateInvoiceDialog:superClass().onGuiSetupFinished(self)
end

function CreateInvoiceDialog:onOpen()
  CreateInvoiceDialog:superClass().onOpen(self)

  -- If there is an invoiceDraft in the current session, set it
  if g_currentMission.CustomContracts.invoiceDraft ~= nil then
    self.invoiceDraft = g_currentMission.CustomContracts.invoiceDraft
  else
    g_currentMission.CustomContracts.invoiceDraft = self.invoiceDraft
  end

  if self.titleInput ~= nil then
    self.titleInput:setText("")
  end

  if self.descriptionInput ~= nil then
    self.descriptionInput:setText("")
  end

  -- Set the invoiceLine smoothlist
  self.invoiceLineTable:setDataSource(self.linesRenderer)
  self.invoiceLineTable:setDelegate(self.linesRenderer)

  -- Retrieve the current farmId
  local myFarmId = g_currentMission:getFarmId()

  -- Setup receiver farm MultiTextOption
  self.receiverFarmIds = {}

  local farmsTexts = {}

  for _, farm in ipairs(g_farmManager.farms) do
    local farmId = farm.farmId
    if farmId ~= FarmManager.SPECTATOR_FARM_ID and farm.showInFarmScreen and farmId ~= myFarmId then
      table.insert(self.receiverFarmIds, farmId)
      table.insert(farmsTexts, farm.name)
    end
  end

  self.receiverSelector:setTexts(farmsTexts)
  self.selectedReceiverFarmIndex = 1
  self.receiverSelector:setState(1, false)

  -- Set the due date MultiTextOption
  self:fillMonthMultiTextOption(self.dueDateSelector, "dueDateValues")
  self.selectedDueDateIndex = 1
  self.dueDateSelector:setState(1, true)

  -- default empty lines if no draft
  if self.invoiceDraft == nil then
    self.linesRenderer:setData({})
  else
    self:applyDraftToUi(self.invoiceDraft)
  end

  self.invoiceLineTable:reloadData()
  self:updateTotalFromLines()
end

function CreateInvoiceDialog:onClose()
  CreateInvoiceDialog:superClass().onClose(self)
end

function CreateInvoiceDialog:onGroupSelectChange(state)
  self.selectedReceiverFarmIndex = state
end

function CreateInvoiceDialog:onDueDateSelectChange(state)
  self.selectedDueDateIndex = state
end

function CreateInvoiceDialog:onSaveAsDraft(sender)
  if g_client == nil then return end

  local title             = self.titleInput:getText() or ""
  title                   = title:gsub("^%s+", ""):gsub("%s+$", "")

  -- Description
  local description       = self.descriptionInput:getText() or ""
  description             = description:gsub("^%s+", ""):gsub("%s+$", "")

  -- Receiver farmId (from selector)
  local receiverFarmId    = self.receiverFarmIds[self.selectedReceiverFarmIndex]

  -- Total
  local total             = self:calculateTotalFromDraftLines()

  -- Validation
  local creatorFarmId     = (g_currentMission ~= nil and g_currentMission:getFarmId()) or FarmManager.SPECTATOR_FARM_ID

  local dueV              = self.dueDateValues[self.selectedDueDateIndex or 1]

  local cc                = g_currentMission.CustomContracts
  local lines             = cc.invoiceDraft and cc.invoiceDraft.lines or {}

  local relatedContractId = (cc.invoiceDraft and cc.invoiceDraft.relatedContractId) or -1
  local autoGenerated     = (cc.invoiceDraft and cc.invoiceDraft.autoGenerated == true) or false

  -- Setup the payload for the new invoice
  local payload           = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.DRAFT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    dueAt = dueV.period,
    relatedContractId = relatedContractId,
    autoGenerated = autoGenerated
  }

  g_client:getServerConnection():sendEvent(CreateInvoiceEvent.new(payload, creatorFarmId))

  g_currentMission.CustomContracts.invoiceDraft = nil
  self:close()
end

-- XML onClick handlers
function CreateInvoiceDialog:onConfirm(sender)
  if g_client == nil then
    return
  end

  local title          = self.titleInput:getText() or ""
  title                = title:gsub("^%s+", ""):gsub("%s+$", "")

  -- Description
  local description    = self.descriptionInput:getText() or ""
  description          = description:gsub("^%s+", ""):gsub("%s+$", "")

  -- Receiver farmId (from selector)
  local receiverFarmId = self.receiverFarmIds[self.selectedReceiverFarmIndex]

  -- Total
  local total          = self:calculateTotalFromDraftLines()

  -- Validation
  local creatorFarmId  = (g_currentMission ~= nil and g_currentMission:getFarmId()) or FarmManager.SPECTATOR_FARM_ID

  -- Optional: due date. If you don’t have UI yet, set 0.
  -- Later you can add a due selector and pass it here.
  local dueIdx         = self.selectedDueDateIndex or 1
  local dueV           = self.dueDateValues[self.selectedDueDateIndex or 1]

  local cc             = g_currentMission.CustomContracts
  local lines          = cc.invoiceDraft and cc.invoiceDraft.lines or {}

  local payload        = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.SENT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    dueAt = dueV.period,
    relatedContractId = -1,
    autoGenerated = false
  }

  g_client:getServerConnection():sendEvent(CreateInvoiceEvent.new(payload, creatorFarmId))

  g_currentMission.CustomContracts.invoiceDraft = nil

  self:close()
end

function CreateInvoiceDialog:onCancel(sender)
  -- Reset all fields.
  if self.titleInput ~= nil then self.titleInput:setText("") end
  if self.descriptionInput ~= nil then self.descriptionInput:setText("") end
  if self.totalInput ~= nil then self.totalInput:setText("") end

  self.selectedReceiverFarmIndex = 1
  self.selectedDueDateIndex = 1

  self:close()
end

function CreateInvoiceDialog:onAddInvoiceLine()
  self:close()

  g_gui:showDialog("addInvoiceLineDialog")
end

function CreateInvoiceDialog:fillMonthMultiTextOption(multiTextOption, valuesFieldName)
  local texts, values = CustomUtils:buildMonthOptionData()

  self[valuesFieldName] = values

  multiTextOption:setTexts(texts)
  multiTextOption:setState(1, true)
end

function CreateInvoiceDialog:setPrefillDraft(draft)
  -- draft is a plain lua table (payload-like)
  local cc = g_currentMission and g_currentMission.CustomContracts
  if cc ~= nil then
    cc.invoiceDraft = draft
  end
end

function CreateInvoiceDialog:applyDraftToUi(draft)
  if draft == nil then return end

  -- title/description/total
  if self.titleInput ~= nil and draft.title ~= nil then
    self.titleInput:setText(draft.title)
  end
  if self.descriptionInput ~= nil and draft.description ~= nil then
    self.descriptionInput:setText(draft.description)
  end
  if self.totalInput ~= nil and draft.total ~= nil then
    self.totalInput:setText(tostring(draft.total))
  end

  -- receiver selector -> find matching farmId
  if draft.receiverFarmId ~= nil and self.receiverFarmIds ~= nil then
    for i, id in ipairs(self.receiverFarmIds) do
      if id == draft.receiverFarmId then
        self.selectedReceiverFarmIndex = i
        self.receiverSelector:setState(i, false)
        break
      end
    end
  end

  -- due selector -> find matching period (your dueAt = period)
  if draft.dueAt ~= nil and self.dueDateValues ~= nil then
    for i, v in ipairs(self.dueDateValues) do
      if v.period == draft.dueAt then
        self.selectedDueDateIndex = i
        self.dueDateSelector:setState(i, true)
        break
      end
    end
  end

  -- lines
  self.linesRenderer:setData(draft.lines)
  self:updateTotalFromLines()
end

function CreateInvoiceDialog:calculateTotalFromDraftLines()
  local total = 0

  if self.invoiceDraft.lines ~= nil then
    for _, line in ipairs(self.invoiceDraft.lines) do
      total = total + (tonumber(line.amount) or 0)
    end
  end

  -- invoice total is int in your code, so round to int
  return math.floor(total + 0.5)
end

function CreateInvoiceDialog:updateTotalFromLines()
  if self.totalInput == nil then return end
  local total = self:calculateTotalFromDraftLines()
  self.totalInput:setText(tostring(total))
end
