--
-- FS25 CustomContracts
--
-- @Author: Racc00n
-- @Version: 0.0.1.1
--

CreateInvoiceDialog = {}
local CreateInvoiceDialog_mt = Class(CreateInvoiceDialog, MessageDialog)


function CreateInvoiceDialog.new(target, custom_mt)
  local self = MessageDialog.new(target, custom_mt or CreateInvoiceDialog_mt)
  return self
end

function CreateInvoiceDialog:onCreate()
  CreateInvoiceDialog:superClass().onCreate(self)
  self.linesRenderer = InvoiceLinesRenderer.new()
end

function CreateInvoiceDialog:onGuiSetupFinished()
  CreateInvoiceDialog:superClass().onGuiSetupFinished(self)
end

function CreateInvoiceDialog:onOpen()
  CreateInvoiceDialog:superClass().onOpen(self)

  self.invoiceLineTable:setDataSource(self.linesRenderer)
  self.invoiceLineTable:setDelegate(self.linesRenderer)

  local myFarmId = g_currentMission:getFarmId()

  self.receiverFarmIds = {}
  local farmsTexts = {}

  for _, farm in ipairs(g_farmManager.farms) do
    local farmId = farm.farmId

    if farmId ~= FarmManager.SPECTATOR_FARM_ID
        and farm.showInFarmScreen
        and farmId ~= myFarmId then
      table.insert(self.receiverFarmIds, farmId)
      table.insert(farmsTexts, farm.name)
    end
  end

  self.receiverSelector:setTexts(farmsTexts)
  self.receiverSelector:setState(1, false)

  self.selectedReceiverFarmIndex = 1

  self:fillMonthMultiTextOption(self.dueDateSelector, "dueDateValues")
  self.selectedDueDateIndex = 1

  if g_currentMission.CustomContracts.invoiceDraft ~= nil then
    self.linesRenderer:setData(g_currentMission.CustomContracts.invoiceDraft.lines)
  end

  -- ✅ now the list knows how many rows exist
  self.invoiceLineTable:reloadData()
end

function CreateInvoiceDialog:onClose()
  CreateInvoiceDialog:superClass().onClose(self)
end

function CreateInvoiceDialog:onGroupSelectChange(state)
  self.selectedReceiverFarmIndex = state
end

function CreateInvoiceDialog:onDueDateSelectChange(state)
  self.selectedDueDateIndex = state
end

function CreateInvoiceDialog:onSaveAsDraft(sender)
  if g_client == nil then
    return
  end

  local title          = self.titleInput:getText() or ""
  title                = title:gsub("^%s+", ""):gsub("%s+$", "")

  -- Description
  local description    = self.descriptionInput:getText() or ""
  description          = description:gsub("^%s+", ""):gsub("%s+$", "")

  -- Receiver farmId (from selector)
  local receiverFarmId = self.receiverFarmIds[self.selectedReceiverFarmIndex]

  -- Total (int, >= 1)
  local totalText      = self.totalInput:getText() or ""
  totalText            = totalText:gsub(",", ".")      -- allow "1,5" typing
  local totalNumber    = tonumber(totalText) or 0
  local total          = math.floor(totalNumber + 0.5) -- round to int

  -- Validation
  local creatorFarmId  = (g_currentMission ~= nil and g_currentMission:getFarmId()) or FarmManager.SPECTATOR_FARM_ID

  -- Optional: due date. If you don’t have UI yet, set 0.
  -- Later you can add a due selector and pass it here.
  local dueIdx         = self.selectedDueDateIndex or 1
  local dueV           = self.dueDateValues[self.selectedDueDateIndex or 1]

  local cc             = g_currentMission.CustomContracts
  local lines          = cc.invoiceDraft and cc.invoiceDraft.lines or {}

  local payload        = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.DRAFT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    dueAt = dueV.period,
    relatedContractId = -1,
    autoGenerated = false
  }

  g_client:getServerConnection():sendEvent(CreateInvoiceEvent.new(payload, creatorFarmId))

  self:close()
end

-- XML onClick handlers
function CreateInvoiceDialog:onConfirm(sender)
  if g_client == nil then
    return
  end

  local title          = self.titleInput:getText() or ""
  title                = title:gsub("^%s+", ""):gsub("%s+$", "")

  -- Description
  local description    = self.descriptionInput:getText() or ""
  description          = description:gsub("^%s+", ""):gsub("%s+$", "")

  -- Receiver farmId (from selector)
  local receiverFarmId = self.receiverFarmIds[self.selectedReceiverFarmIndex]

  -- Total (int, >= 1)
  local totalText      = self.totalInput:getText() or ""
  totalText            = totalText:gsub(",", ".")      -- allow "1,5" typing
  local totalNumber    = tonumber(totalText) or 0
  local total          = math.floor(totalNumber + 0.5) -- round to int

  -- Validation
  local creatorFarmId  = (g_currentMission ~= nil and g_currentMission:getFarmId()) or FarmManager.SPECTATOR_FARM_ID

  -- Optional: due date. If you don’t have UI yet, set 0.
  -- Later you can add a due selector and pass it here.
  local dueIdx         = self.selectedDueDateIndex or 1
  local dueV           = self.dueDateValues[self.selectedDueDateIndex or 1]

  local cc             = g_currentMission.CustomContracts
  local lines          = cc.invoiceDraft and cc.invoiceDraft.lines or {}

  local payload        = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.SENT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    dueAt = dueV.period,
    relatedContractId = -1,
    autoGenerated = false
  }

  g_client:getServerConnection():sendEvent(CreateInvoiceEvent.new(payload, creatorFarmId))

  self:close()
end

function CreateInvoiceDialog:onCancel(sender)
  self:close()
end

function CreateInvoiceDialog:onAddInvoiceLine()
  self:close()
  g_gui:showDialog("addInvoiceLineDialog")
end

function CreateInvoiceDialog:fillMonthMultiTextOption(multiTextOption, valuesFieldName)
  local texts, values = CustomUtils:buildMonthOptionData()

  self[valuesFieldName] = values

  multiTextOption:setTexts(texts)
  multiTextOption:setState(1, true)
end
