--
-- FS25 Contract and Invoices
--
-- @Author: Racc00n
-- @Version: 1.0.0.0
--

EditInvoiceDialog = {}
local EditInvoiceDialog_mt = Class(EditInvoiceDialog, MessageDialog)
local modDirectory = g_currentModDirectory

function EditInvoiceDialog.register()
  local dialog = EditInvoiceDialog.new()
  g_gui:loadGui(modDirectory .. "gui/dialog/invoices/EditInvoiceDialog.xml", "editInvoiceDialog", dialog)
  EditInvoiceDialog.INSTANCE = dialog
end

function EditInvoiceDialog.new(target, custom_mt)
  local dialog = MessageDialog.new(target, custom_mt or EditInvoiceDialog_mt)

  return dialog
end

function EditInvoiceDialog.show(invoice)
  if EditInvoiceDialog.INSTANCE == nil then EditInvoiceDialog.register() end

  local dialog = EditInvoiceDialog.INSTANCE


  if invoice ~= nil then
    dialog.invoice = invoice
  end

  g_gui:showDialog("editInvoiceDialog")
end

function EditInvoiceDialog:onCreate()
  EditInvoiceDialog:superClass().onCreate(self)
  self.linesRenderer = InvoiceLinesRenderer.new()
end

function EditInvoiceDialog:onGuiSetupFinished()
  EditInvoiceDialog:superClass().onGuiSetupFinished(self)
end

function EditInvoiceDialog:onOpen()
  EditInvoiceDialog:superClass().onOpen(self)

  FocusManager:setFocus(self.titleInput)
  self.titleInput.blockTime = 0
  self.titleInput:onFocusActivate()

  -- Set the invoiceLine smoothlist
  self.invoiceLineTable:setDataSource(self.linesRenderer)
  self.invoiceLineTable:setDelegate(self.linesRenderer)

  -- Retrieve the current farmId
  local myFarmId = g_currentMission:getFarmId()

  -- Setup receiver farm MultiTextOption
  self.receiverFarmIds = {}

  local farmsTexts = {}

  for _, farm in ipairs(g_farmManager.farms) do
    local farmId = farm.farmId
    if farmId ~= FarmManager.SPECTATOR_FARM_ID and farm.showInFarmScreen and farmId ~= myFarmId then
      table.insert(self.receiverFarmIds, farmId)
      table.insert(farmsTexts, farm.name)
    end
  end

  self.receiverSelector:setTexts(farmsTexts)
  self.selectedReceiverFarmIndex = 1
  self.receiverSelector:setState(1, false)

  -- default empty lines if no draft
  if self.invoice == nil then
    self.linesRenderer:setData({})
  else
    self:applyDraftToUi(self.invoice)
    self:updateTotalFromLines()
  end

  self.invoiceLineTable:reloadData()
end

function EditInvoiceDialog:onClose()
  EditInvoiceDialog:superClass().onClose(self)
end

function EditInvoiceDialog:onGroupSelectChange(state)
  self.selectedReceiverFarmIndex = state
end

function EditInvoiceDialog:onRelatedContractSelectChange(state)
  self.selectedRelatedContractIndex = state
end

function EditInvoiceDialog:onSaveAsDraft(sender)
  if g_client == nil then return end

  local title             = self.titleInput:getText() or ""
  local description       = self.descriptionInput:getText() or ""
  local receiverFarmId    = self.receiverFarmIds[self.selectedReceiverFarmIndex]
  local total             = self:calculateTotalFromDraftLines()
  local creatorFarmId     = g_currentMission:getFarmId()
  local lines             = self.invoice.lines
  local relatedContractId = self.invoice.relatedContractId or -1
  local autoGenerated     = self.invoice.autoGenerated or false

  -- Setup the payload for the new invoice
  local payload           = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.DRAFT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    relatedContractId = relatedContractId,
    autoGenerated = autoGenerated
  }

  g_client:getServerConnection():sendEvent(EditInvoiceEvent.new(self.invoice.id, payload))

  self:close()
end

function EditInvoiceDialog:onConfirm(sender)
  if g_client == nil then
    return
  end

  local title             = self.titleInput:getText() or ""
  local description       = self.descriptionInput:getText() or ""
  local receiverFarmId    = self.receiverFarmIds[self.selectedReceiverFarmIndex]
  local total             = self:calculateTotalFromDraftLines()
  local creatorFarmId     = g_currentMission:getFarmId()
  local lines             = self.invoice.lines
  local relatedContractId = self.invoice.relatedContractId or -1
  local autoGenerated     = self.invoice.autoGenerated or false

  local payload           = {
    receiverFarmId = receiverFarmId,
    status = Invoice.STATUS.SENT,
    title = title,
    description = description,
    lines = lines,
    total = total,
    relatedContractId = relatedContractId,
    autoGenerated = autoGenerated
  }

  g_client:getServerConnection():sendEvent(EditInvoiceEvent.new(self.invoice.id, payload))

  self:close()
end

function EditInvoiceDialog:onCancel(sender)
  self.invoice = {
    title = "",
    description = "",
    receiverFarmId = nil,
    lines = {},
    total = 0,
    relatedContractId = nil,
    autoGenerated = false
  }
  self:close()
end

function EditInvoiceDialog:onAddInvoiceLine()
  self:storeUiToDraft()
  self:close()

  AddInvoiceLineDialog.show(self.invoice, function(draft)
    EditInvoiceDialog.show(draft)
  end)
end

function EditInvoiceDialog:storeUiToDraft()
  if self.invoice == nil then return end

  self.invoice.title = self.titleInput and (self.titleInput:getText() or "") or (self.invoice.title or "")
  self.invoice.description = self.descriptionInput and (self.descriptionInput:getText() or "") or
      (self.invoice.description or "")
  self.invoice.receiverFarmId = self.receiverFarmIds and self.selectedReceiverFarmIndex and
      self.receiverFarmIds[self.selectedReceiverFarmIndex] or self.invoice.receiverFarmId
  self.invoice.total = self:calculateTotalFromDraftLines()
end

function EditInvoiceDialog:applyDraftToUi(draft)
  if draft == nil then return end

  -- title/description/total
  if self.titleInput ~= nil and draft.title ~= nil then
    self.titleInput:setText(draft.title)
  end
  if self.descriptionInput ~= nil and draft.description ~= nil then
    self.descriptionInput:setText(draft.description)
  end
  if self.totalInput ~= nil and draft.total ~= nil then
    self.totalInput:setText(tostring(draft.total))
  end

  -- receiver selector -> find matching farmId
  if draft.receiverFarmId ~= nil and self.receiverFarmIds ~= nil then
    for i, id in ipairs(self.receiverFarmIds) do
      if id == draft.receiverFarmId then
        self.selectedReceiverFarmIndex = i
        self.receiverSelector:setState(i, false)
        break
      end
    end
  end

  -- lines
  self.linesRenderer:setData(draft.lines)
  self:updateTotalFromLines()
end

function EditInvoiceDialog:calculateTotalFromDraftLines()
  local total = 0

  if self.invoice ~= nil then
    if #self.invoice.lines > 0 then
      for _, line in ipairs(self.invoice.lines) do
        total = total + (tonumber(line.amount) or 0)
      end
    else
      return tonumber(self.totalInput:getText())
    end
  end

  return math.floor(total + 0.5)
end

function EditInvoiceDialog:updateTotalFromLines()
  if self.totalInput == nil then return end
  local total = self:calculateTotalFromDraftLines()
  self.totalInput:setText(tostring(total))
end
