InvoiceManager = {}
InvoiceManager_mt = Class(InvoiceManager)
InvoiceManager.dir = g_currentModDirectory
InvoiceManager.modName = g_currentModName

function InvoiceManager.new()
  print("loaded")
  local self = setmetatable({}, InvoiceManager_mt)

  self.invoices = {}
  self.nextId = 1

  MoneyType.INVOICES = MoneyType.register("invoices", "cc_money_type_invoices")
  MoneyType.LAST_ID = MoneyType.LAST_ID + 1

  if g_currentMission:getIsServer() then
    g_messageCenter:subscribe(
      MessageType.PLAYER_CONNECTED,
      self.onPlayerConnected,
      self
    )
  end

  return self
end

function InvoiceManager:saveToXmlFile(xmlFile)
  if not g_currentMission:getIsServer() then return end

  local key = CustomContracts.SaveKey
  local count = 0

  for id, invoice in pairs(self.invoices) do
    local invKey = string.format("%s.invoice(%d)", key, count)

    setXMLInt(xmlFile, invKey .. "#id", invoice.id)
    setXMLString(xmlFile, invKey .. "#number", invoice.number or "")
    setXMLInt(xmlFile, invKey .. "#creatorFarmId", invoice.creatorFarmId)
    setXMLInt(xmlFile, invKey .. "#receiverFarmId", invoice.receiverFarmId)
    setXMLString(xmlFile, invKey .. "#status", invoice.status or Invoice.STATUS.DRAFT)
    setXMLString(xmlFile, invKey .. "#currency", invoice.currency or "EUR")
    setXMLInt(xmlFile, invKey .. "#createdAt", invoice.createdAt)
    setXMLInt(xmlFile, invKey .. "#sentAt", invoice.sentAt or 0)
    setXMLInt(xmlFile, invKey .. "#dueAt", invoice.dueAt)
    setXMLInt(xmlFile, invKey .. "#paidAt", invoice.paidAt or 0)
    setXMLString(xmlFile, invKey .. "#title", invoice.title)
    setXMLString(xmlFile, invKey .. "#description", invoice.description or "")
    setXMLInt(xmlFile, invKey .. "#total", invoice.total)
    setXMLInt(xmlFile, invKey .. "#paid", invoice.paid or 0)
    setXMLInt(xmlFile, invKey .. "#remaining", invoice.remaining or 0) -- future: partial payments
    setXMLInt(xmlFile, invKey .. "#relatedContractId", invoice.relatedContractId or -1)
    setXMLBool(xmlFile, invKey .. "#autoGenerated", invoice.autoGenerated == true)
    setXMLString(xmlFile, invKey .. "#meta", invoice.meta or "")
    self:saveInvoiceLinesToXml(xmlFile, invKey, invoice.lines)

    count = count + 1
  end
end

function InvoiceManager:loadFromXmlFile(xmlFile)
  if not g_currentMission:getIsServer() then return end

  self.invoices = {}
  self.nextId = 1

  local key = CustomContracts.SaveKey
  local i = 0

  while true do
    local invoiceKey = string.format("%s.invoice(%d)", key, i)
    if not hasXMLProperty(xmlFile, invoiceKey) then
      break
    end

    local id                = getXMLInt(xmlFile, invoiceKey .. "#id")
    local number            = getXMLString(xmlFile, invoiceKey .. "#number")
    local creatorFarmId     = getXMLInt(xmlFile, invoiceKey .. "#creatorFarmId")
    local receiverFarmId    = getXMLInt(xmlFile, invoiceKey .. "#receiverFarmId")
    local status            = getXMLString(xmlFile, invoiceKey .. "#status")
    local currency          = getXMLString(xmlFile, invoiceKey .. "#currency")
    local createdAt         = getXMLInt(xmlFile, invoiceKey .. "#createdAt")
    local sentAt            = getXMLInt(xmlFile, invoiceKey .. "#sentAt")
    local dueAt             = getXMLInt(xmlFile, invoiceKey .. "#dueAt")
    local paidAt            = getXMLInt(xmlFile, invoiceKey .. "#paidAt")
    local title             = getXMLString(xmlFile, invoiceKey .. "#title")
    local description       = getXMLString(xmlFile, invoiceKey .. "#description")
    local total             = getXMLInt(xmlFile, invoiceKey .. "#total")
    local paid              = getXMLInt(xmlFile, invoiceKey .. "#paid")
    local remaining         = getXMLInt(xmlFile, invoiceKey .. "#remaining")
    local relatedContractId = getXMLInt(xmlFile, invoiceKey .. "#relatedContractId")
    local autoGenerated     = getXMLBool(xmlFile, invoiceKey .. "#autoGenerated")
    local meta              = getXMLString(xmlFile, invoiceKey .. "#meta")

    local invoice           = Invoice.new(
      id,
      creatorFarmId,
      receiverFarmId,
      status or Invoice.STATUS.DRAFT,
      createdAt,
      sentAt,
      dueAt,
      paidAt,
      title,
      description,
      total,
      paid,
      relatedContractId ~= -1 and relatedContractId or nil,
      autoGenerated
    )

    invoice.number          = number
    invoice.currency        = currency or "EUR"
    invoice.remaining       = remaining or 0
    invoice.meta            = meta ~= "" and meta or nil

    invoice.lines           = self:loadInvoiceLinesFromXml(xmlFile, invoiceKey)

    self.invoices[id]       = invoice
    self.nextId             = math.max(self.nextId or 1, id + 1)

    i                       = i + 1
  end

  -- TODO: Add call syncInvoices function
  self:syncInvoices()
end

function InvoiceManager:writeInitialClientState(streamId, connection)
  streamWriteInt32(streamId, self.nextId)

  local count = table.size(self.invoices)
  streamWriteInt32(streamId, count)

  for _, invoice in pairs(self.invoices) do
    invoice:writeStream(streamId)
  end
end

function InvoiceManager:readInitialClientState(streamId, connection)
  self.invoices = {}

  self.nextId = streamReadInt32(streamId)
  local count = streamReadInt32(streamId)

  for i = 1, count do
    local invoice = Invoice.newFromStream(streamId)
    self.invoices[invoice.id] = invoice
  end

  g_messageCenter:publish(MessageType.INVOICES_UPDATED)
end

function InvoiceManager:syncInvoices(connection)
  if not g_currentMission:getIsServer() then return end

  local event = SyncInvoicesEvent.new(self.invoices, self.nextId)

  if connection ~= nil then
    print("Send")
    connection:sendEvent(event)
  else
    print("send 2")
    g_server:broadcastEvent(event, true)
  end
end

function InvoiceManager:onPlayerConnected(connection)
  if not g_currentMission:getIsServer() then return end
  if connection == nil then return end

  self:syncInvoices(connection)
end

function InvoiceManager:getInvoicesByCurrentFarm()
  local invoices = {}

  local farmId = g_currentMission:getFarmId();
  if farmId == nil or farmId == 0 then
    return invoices
  end

  for _, invoice in pairs(self.invoices) do
    local isCreator  = invoice.creatorFarmId == farmId
    local isReceiver = invoice.receiverFarmId == farmId

    -- Creator sees everything
    if isCreator then
      table.insert(invoices, invoice)

      -- Receiver only sees non-draft invoices
    elseif isReceiver and invoice.status ~= Invoice.STATUS.DRAFT then
      table.insert(invoices, invoice)
    end
  end

  return invoices
end

function InvoiceManager:handleCreateRequest(farmId, payload)
  if not g_currentMission:getIsServer() then return end

  local id          = self.nextId
  self.nextId       = self.nextId + 1

  local invoice     = Invoice.new(
    id,
    farmId,
    payload.receiverFarmId,
    payload.status or Invoice.STATUS.DRAFT,
    g_currentMission.time, -- createdAt
    0,                   -- sentAt
    payload.dueAt or 0,
    0,                   -- paidAt
    payload.title,
    payload.description,
    payload.total,
    0, -- paid
    payload.relatedContractId ~= -1 and payload.relatedContractId or nil,
    payload.autoGenerated == true
  )

  -- generate readable invoice number
  invoice.number    = string.format("CC-INV-%06d", id)
  invoice.lines     = payload.lines or {}

  self.invoices[id] = invoice

  self:syncInvoices()
end

function InvoiceManager:handleSendRequest(invoiceId)
  if not g_currentMission:getIsServer() then return end

  local invoice = self.invoices[invoiceId]

  invoice.status = Invoice.STATUS.SENT

  self:syncInvoices()
end

function InvoiceManager:handlePayRequest(farmId, invoiceId)
  if not g_currentMission:getIsServer() then return end

  local invoice = self.invoices[invoiceId]

  -- TODO: Add notification to the creator farm that money is low
  -- if g_farmManager:getFarmById(invoice.creatorFarmId).money < invoice.total then
  --   return
  -- end

  if g_currentMission:getIsServer() then
    -- Remove money from receiver farm
    g_currentMission:addMoneyChange(
      -invoice.total,
      invoice.receiverFarmId,
      MoneyType.INVOICES,
      true
    )

    -- Pay the creator farm
    g_currentMission:addMoneyChange(
      invoice.total,
      invoice.creatorFarmId,
      MoneyType.INVOICES,
      true
    )
  end

  g_farmManager:getFarmById(invoice.receiverFarmId):changeBalance(-invoice.total, MoneyType.INVOICES)
  g_farmManager:getFarmById(invoice.creatorFarmId):changeBalance(invoice.total, MoneyType.INVOICES)

  -- Change status of contract to be completed
  invoice.status = Invoice.STATUS.PAID

  -- Update all clients
  self:syncInvoices()
end

function InvoiceManager:saveInvoiceLinesToXml(xmlFile, invKey, lines)
  lines = lines or {}
  local linesKey = invKey .. ".lines"

  setXMLInt(xmlFile, linesKey .. "#count", #lines)

  for i, line in ipairs(lines) do
    local lineKey = string.format("%s.line(%d)", linesKey, i - 1)
    setXMLString(xmlFile, lineKey .. "#title", line.title or "")
    setXMLFloat(xmlFile, lineKey .. "#amount", tonumber(line.amount) or 0)
  end
end

function InvoiceManager:loadInvoiceLinesFromXml(xmlFile, invKey)
  local lines = {}
  local linesKey = invKey .. ".lines"

  if not hasXMLProperty(xmlFile, linesKey) then
    return lines
  end

  local count = getXMLInt(xmlFile, linesKey .. "#count") or 0
  for i = 0, count - 1 do
    local lineKey = string.format("%s.line(%d)", linesKey, i)
    local title = getXMLString(xmlFile, lineKey .. "#title") or ""
    local amount = getXMLFloat(xmlFile, lineKey .. "#amount") or 0
    table.insert(lines, { title = title, amount = amount })
  end

  return lines
end
