InvoiceManager = {}
InvoiceManager_mt = Class(InvoiceManager)
InvoiceManager.dir = g_currentModDirectory
InvoiceManager.modName = g_currentModName

function InvoiceManager.new()
  print("loaded")
  local self = setmetatable({}, InvoiceManager_mt)

  self.invoices = {}
  self.nextId = 1

  if g_currentMission:getIsServer() then
    g_messageCenter:subscribe(
      MessageType.PLAYER_CONNECTED,
      self.onPlayerConnected,
      self
    )
  end

  return self
end

function InvoiceManager:saveToXmlFile(xmlFile)
  if not g_currentMission:getIsServer() then return end

  local key = CustomContracts.SaveKey
  local count = 0

  for id, invoice in pairs(self.invoices) do
    local invKey = string.format("%s.invoice(%d)", key, count)

    setXMLInt(xmlFile, invKey .. "#id", invoice.id)
    setXMLString(xmlFile, invKey .. "#number", invoice.number or "")
    setXMLInt(xmlFile, invKey .. "#creatorFarmId", invoice.creatorFarmId)
    setXMLInt(xmlFile, invKey .. "#receiverFarmId", invoice.receiverFarmId)
    setXMLString(xmlFile, invKey .. "#status", invoice.status or Invoice.STATUS.DRAFT)
    setXMLString(xmlFile, invKey .. "#currency", invoice.currency or "EUR")
    setXMLInt(xmlFile, invKey .. "#createdAt", invoice.createdAt)
    setXMLInt(xmlFile, invKey .. "#sentAt", invoice.sentAt or 0)
    setXMLInt(xmlFile, invKey .. "#dueAt", invoice.dueAt)
    setXMLInt(xmlFile, invKey .. "#paidAt", invoice.paidAt or 0)
    setXMLString(xmlFile, invKey .. "#title", invoice.title)
    setXMLString(xmlFile, invKey .. "#description", invoice.description or "")
    setXMLInt(xmlFile, invKey .. "#total", invoice.total)
    setXMLInt(xmlFile, invKey .. "#paid", invoice.paid or 0)
    setXMLInt(xmlFile, invKey .. "#remaining", invoice.remaining or 0) -- future: partial payments
    setXMLInt(xmlFile, invKey .. "#relatedContractId", invoice.relatedContractId or -1)
    setXMLBool(xmlFile, invKey .. "#autoGenerated", invoice.autoGenerated == true)
    setXMLString(xmlFile, invKey .. "#meta", invoice.meta or "")

    count = count + 1
  end
end

function InvoiceManager:loadFromXmlFile(xmlFile)
  if not g_currentMission:getIsServer() then return end

  self.invoices = {}
  self.nextId = 1

  local key = CustomContracts.SaveKey
  local i = 0

  while true do
    local invoiceKey = string.format("%s.invoice(%d)", key, i)
    if not hasXMLProperty(xmlFile, invoiceKey) then
      break
    end

    local id                = getXMLInt(xmlFile, invoiceKey .. "#id")
    local number            = getXMLString(xmlFile, invoiceKey .. "#number")
    local creatorFarmId     = getXMLInt(xmlFile, invoiceKey .. "#creatorFarmId")
    local receiverFarmId    = getXMLInt(xmlFile, invoiceKey .. "#receiverFarmId")
    local status            = getXMLString(xmlFile, invoiceKey .. "#status")
    local currency          = getXMLString(xmlFile, invoiceKey .. "#currency")
    local createdAt         = getXMLInt(xmlFile, invoiceKey .. "#createdAt")
    local sentAt            = getXMLInt(xmlFile, invoiceKey .. "#sentAt")
    local dueAt             = getXMLInt(xmlFile, invoiceKey .. "#dueAt")
    local paidAt            = getXMLInt(xmlFile, invoiceKey .. "#paidAt")
    local title             = getXMLString(xmlFile, invoiceKey .. "#title")
    local description       = getXMLString(xmlFile, invoiceKey .. "#description")
    local total             = getXMLInt(xmlFile, invoiceKey .. "#total")
    local paid              = getXMLInt(xmlFile, invoiceKey .. "#paid")
    local remaining         = getXMLInt(xmlFile, invoiceKey .. "#remaining")
    local relatedContractId = getXMLInt(xmlFile, invoiceKey .. "#relatedContractId")
    local autoGenerated     = getXMLBool(xmlFile, invoiceKey .. "#autoGenerated")
    local meta              = getXMLString(xmlFile, invoiceKey .. "#meta")

    local invoice           = Invoice.new(
      id,
      creatorFarmId,
      receiverFarmId,
      createdAt,
      sentAt,
      dueAt,
      paidAt,
      title,
      description,
      total,
      paid,
      relatedContractId ~= -1 and relatedContractId or nil,
      autoGenerated
    )

    invoice.number          = number
    invoice.status          = status
    invoice.currency        = currency or "EUR"
    invoice.remaining       = remaining or 0
    invoice.meta            = meta ~= "" and meta or nil

    self.invoices[id]       = invoice
    self.nextInvoiceId      = math.max(self.nextInvoiceId or 1, id + 1)

    i                       = i + 1
  end

  -- TODO: Add call syncInvoices function
  self:syncInvoices()
end

function InvoiceManager:writeInitialClientState(streamId, connection)
  streamWriteInt32(streamId, self.nextId)

  local count = table.size(self.invoices)
  streamWriteInt32(streamId, count)

  for _, invoice in pairs(self.invoices) do
    invoice:writeStream(streamId)
  end
end

function InvoiceManager:readInitialClientState(streamId, connection)
  self.invoices = {}

  self.nextId = streamReadInt32(streamId)
  local count = streamReadInt32(streamId)

  for i = 1, count do
    local invoice = Invoice.newFromStream(streamId)
    self.invoices[invoice.id] = invoice
  end

  g_messageCenter:publish(MessageType.INVOICES_UPDATED)
end

function InvoiceManager:syncInvoices(connection)
  if not g_currentMission:getIsServer() then return end

  local event = SyncInvoicesEvent.new(self.invoices, self.nextId)

  if connection ~= nil then
    connection:sendEvent(event)
  else
    g_server:broadcastEvent(event, true)
  end
end

function InvoiceManager:onPlayerConnected(connection)
  if not g_currentMission:getIsServer() then return end
  if connection == nil then return end

  self:syncInvoices(connection)
end

function InvoiceManager:handleCreateRequest(farmId, payload)
  if not g_currentMission:getIsServer() then return end

  local id = self.nextId
  self.nextId = self.nextId + 1

  local invoice = Invoice.new(
    id,
    farmId,
    payload.receiverFarmId,
    g_currentMission.time, -- createdAt
    0,                     -- sentAt
    payload.dueAt or 0,
    0,                     -- paidAt
    payload.title,
    payload.description,
    payload.total,
    0, -- paid
    payload.relatedContractId ~= -1 and payload.relatedContractId or nil,
    payload.autoGenerated == true
  )

  -- generate readable invoice number
  invoice.number = string.format("CC-INV-%06d", id)

  self.invoices[id] = invoice

  self:syncInvoices()
end
