Invoice = {}
Invoice.dir = g_currentModDirectory
Invoice.modName = g_currentModName
Invoice.__index = Invoice
Invoice_mt = Class(Invoice)

Invoice.STATUS = {
  DRAFT = "DRAFT",
  SENT = "SENT",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  OVERDUE = "OVERDUE",
  DISPUTED = "DISPUTED"
}

function Invoice.new(id, creatorFarmId, receiverFarmId, createdAt, sentAt, dueAt, paidAt, title, description, total, paid,
                     relatedContractId, autoGenerated)
  local self = setmetatable({}, Invoice_mt)

  self.id = id                               -- General id
  self.number = "CC-INV-000123"              -- Generated user friendly id
  self.creatorFarmId = creatorFarmId         -- Who created the invoice
  self.receiverFarmId = receiverFarmId       -- Who must pay
  self.status = Invoice.STATUS.DRAFT         -- Status of the invoice
  self.currency = "EUR"                      -- Which currency (look into it more)
  self.createdAt = createdAt                 -- Date when created
  self.sentAt = sentAt                       -- Date when set to receiver
  self.dueAt = dueAt                         -- Date when invoice must be paid
  self.paidAt = paidAt                       -- Date when invoice is paid by receiver
  self.title = title                         -- Title of the contract
  self.description = description             -- Optional description
  self.lines = nil                           -- Invoicelines (future)
  self.total = total                         -- Total amount that needs to be paid
  self.paid = paid                           -- Amount that is paid (needed for partial payment in the future)
  self.remaining = nil                       -- Partial payment (future)
  self.relatedContractId = relatedContractId -- Link to a contract (optional)
  self.autoGenerated = autoGenerated         -- Boolean wether contract is autoGenerated from contract or not
  self.meta = nil                            -- Future-proof (optional)

  return self
end

function Invoice:writeStream(streamId)
  streamWriteInt32(streamId, self.id)
  streamWriteString(streamId, self.number)
  streamWriteInt32(streamId, self.creatorFarmId)
  streamWriteInt32(streamId, self.receiverFarmId)
  streamWriteString(streamId, self.status)
  streamWriteString(streamId, self.currency)
  streamWriteInt32(streamId, self.createdAt)
  streamWriteInt32(streamId, self.sentAt)
  streamWriteInt32(streamId, self.dueAt)
  streamWriteInt32(streamId, self.paidAt)
  streamWriteString(streamId, self.title)
  streamWriteString(streamId, self.description)
  streamWriteInt32(streamId, self.total)
  streamWriteInt32(streamId, self.paid)
  streamWriteInt32(streamId, self.remaining)
  streamWriteInt32(streamId, self.relatedContractId)
  streamWriteBool(streamId, self.autoGenerated)
  streamWriteString(streamId, self.meta)
end

function Invoice.newFromStream(streamId)
  local id = streamReadInt32(streamId)
  local number = streamReadString(streamId)
  local creatorFarmId = streamReadInt32(streamId)
  local receiverFarmId = streamReadInt32(streamId)
  local status = streamReadString(streamId)
  local currency = streamReadString(streamId)
  local createdAt = streamReadInt32(streamId)
  local sentAt = streamReadInt32(streamId)
  local dueAt = streamReadInt32(streamId)
  local paidAt = streamReadInt32(streamId)
  local title = streamReadString(streamId)
  local description = streamReadString(streamId)
  local total = streamReadInt32(streamId)
  local paid = streamReadInt32(streamId)
  local remaining = streamReadInt32(streamId)
  local relatedContractId = streamReadInt32(streamId)
  local autoGenerated = streamReadBool(streamId)
  local meta = streamReadString(streamId)

  local invoice = Invoice.new(
    id,
    creatorFarmId,
    receiverFarmId,
    createdAt,
    sentAt,
    dueAt,
    paidAt,
    title,
    description,
    total,
    paid,
    relatedContractId,
    autoGenerated
  )

  invoice.number = number
  invoice.status = status
  invoice.currency = currency
  invoice.remaining = remaining
  invoice.meta = meta ~= "" and meta or nil

  return invoice
end
